<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261005193909 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Creates the game module registry table';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game_module (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL, bundle_class VARCHAR(255) NOT NULL, version VARCHAR(30) NOT NULL, description TEXT DEFAULT NULL, icon VARCHAR(255) DEFAULT NULL, cover_image VARCHAR(255) DEFAULT NULL, minimum_age SMALLINT DEFAULT NULL, enabled BOOLEAN NOT NULL, maintenance_mode BOOLEAN NOT NULL, featured BOOLEAN NOT NULL, sort_order INT NOT NULL, supports_guests BOOLEAN NOT NULL, supports_multiplayer BOOLEAN NOT NULL, min_players SMALLINT NOT NULL, max_players SMALLINT DEFAULT NULL, metadata JSON DEFAULT NULL, installed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_enabled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_71118BE0989D9B62 ON game_module (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_71118BE07613AC34 ON game_module (bundle_class)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE game_module');
    }
}
