<?php

declare(strict_types=1);

namespace WouldYouRatherBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261005150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Creates the Would You Rather question table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE would_you (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            question VARCHAR(255) NOT NULL,
            tags JSON NOT NULL,
            category JSON NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            active BOOLEAN NOT NULL,
            option_a VARCHAR(100) NOT NULL,
            option_b VARCHAR(100) NOT NULL,
            PRIMARY KEY(id)
        )');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE would_you');
    }
}